export {default as Nav} from "./Nav"
export {default as HomePage} from "./HomePage"
export {default as News} from "./News"
export {default as CryptoCurrencies} from "./CryptoCurrencies"
export {default as CryptoCurrencyDetails} from "./CryptoCurrencyDetails"
